### PR TITLE
pin pandas<2.1 and add cron trigger to CI

### PR DESCRIPTION
**Pull request by IAlibay**
temporarily addressing #93 and see https://github.com/MDAnalysis/MDAKits/pull/67

### CODE REVIEW

**Comment by IAlibay** [comment]
Ok can confirm it's pandas 2.1 :/

**Review by orbeckst — COMMENTED** [review]
requirements.txt is missing

**Comment by orbeckst** [comment]
For completeness I also pinned in requirements.txt

**Comment by orbeckst** [comment]
The cryptic RTD error 
```
 python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: the following arguments are required: dest
SystemExit: 2 
```
is due to how you have specify conda/mamba in the rtd config file. I just ran into this the other day in https://github.com/Becksteinlab/GromacsWrapper/pull/258 and https://github.com/Becksteinlab/GromacsWrapper/commit/756b8a833c3714f0f5d71434d8020adf462522c5

Let me have a quick look.

**Comment by orbeckst** [comment]
Let's see if just using mambaforge works while letting RTD figure out the rest.

**Comment by orbeckst** [comment]
`docs/requirements.yaml` does not contain pandas... let's see if it works

**Comment by orbeckst** [comment]
This built the docs https://readthedocs.org/projects/solvation-analysis/builds/21958960/ although I am now slightly puzzled because the package wasn't installed. Presumably, sphinx imported the source directly. Check that the docs look right. Then possibly try adding
```yaml
python:
  install:
    - method: pip
      path: .
```
if something needs to be done.

**Comment by orbeckst** [comment]
There are problems on RTD, see https://readthedocs.org/projects/solvation-analysis/builds/21958960/ (last command)
```
Running Sphinx v7.2.6
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
[autosummary] generating autosummary for: api.rst, api/coordination.rst, api/networking.rst, api/pairing.rst, api/plotting.rst, api/residence.rst, api/solute.rst, api/speciation.rst, getting_started.ipynb, index.rst, tutorials.rst, tutorials/basics_tutorial.ipynb, tutorials/clustering_and_residence_tutorial.ipynb, tutorials/multi_atom_solutes.ipynb, tutorials/plotting_tutorial.ipynb, tutorials/rdf_fitting_demo.ipynb, tutorials/visualization_tutorial.ipynb
/home/docs/checkouts/readthedocs.org/user_builds/solvation-analysis/conda/92/lib/python3.11/site-packages/MDAnalysis/topology/TPRParser.py:161: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13
  import xdrlib
WARNING: Failed to import solvation_analysis.plotting.
Possible hints:
* AttributeError: module 'solvation_analysis' has no attribute 'plotting'
* ModuleNotFoundError: No module named 'plotly'
```

**Comment by orbeckst** [comment]
RTD builds so the immediate problem is solved. The issue with plotly can probably be fixed in another PR — I don’t want to add it to the RTD dependencies because I haven’t seen it as a dependency elsewhere. That will require someone with more insight than me.

**Review by hmacdope — APPROVED** [review]

**Comment by orbeckst** [comment]
RTD is happy https://solvation-analysis--92.org.readthedocs.build/en/92/tutorials/plotting_tutorial.html — no complaints about missing packages.

**Comment by orbeckst** [comment]
Thanks for adding plotly, @IAlibay   —- I should have looked more carefully at the other requirement files because it *was* listed elsewhere, I just overlooked it.

**Pull request merged**
